development:
  user: postgres
  password: postgres
  adapter: postgresql
  database: online_store
  host: localhost
  pool: 5
  timeout: 5000
test:
  user: postgres
  password: postgres
  adapter: postgresql
  database: online_store
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: online_store
  pool: 5
  timeout: 5000